import './globals.scss'

export const metadata = {
  title: 'Next.js Route',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} >
        {children}
      </body>
    </html>
  )
}
