
import Footer from 'components/navigation/footer';
import Header from 'components/navigation/header';
export const metadata = {
  title: 'Next Ts - Home',
  description: 'Generated by create next app',
}

export default function LayoutHome({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>

    </html>
  )
}
